import { TopikSection, TopikTier } from '@prisma/client';

/** Ma trận dạng bài TOPIK I — theo số câu trong từng phần (đối chiếu đề 41/91회). */
export type TopikFormatSeed = {
  tier: TopikTier;
  section: TopikSection;
  fromNo: number;
  toNo: number;
  title: string;
  titleKo: string;
  description?: string;
  sortOrder: number;
};

export const TOPIK_I_FORMATS: TopikFormatSeed[] = [
  // —— 듣기 (30 câu) ——
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.LISTENING,
    fromNo: 1,
    toNo: 4,
    title: 'Chọn câu trả lời phù hợp',
    titleKo: '물음에 맞는 대답 고르기',
    description: 'Nghe câu hỏi và chọn đáp án đúng (có <보기>).',
    sortOrder: 1,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.LISTENING,
    fromNo: 5,
    toNo: 6,
    title: 'Chọn câu nói tiếp theo',
    titleKo: '이어지는 말 고르기',
    description: 'Nghe và chọn câu nói tiếp theo phù hợp.',
    sortOrder: 2,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.LISTENING,
    fromNo: 7,
    toNo: 10,
    title: 'Đây là địa điểm nào?',
    titleKo: '여기는 어디입니까?',
    description: 'Nghe hội thoại và xác định địa điểm.',
    sortOrder: 3,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.LISTENING,
    fromNo: 11,
    toNo: 14,
    title: 'Đang nói về chủ đề gì?',
    titleKo: '무엇에 대해 말하고 있습니까?',
    description: 'Nghe và chọn chủ đề của đoạn hội thoại.',
    sortOrder: 4,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.LISTENING,
    fromNo: 15,
    toNo: 16,
    title: 'Chọn hình ảnh phù hợp',
    titleKo: '대화 듣고 알맞은 그림 고르기',
    description: 'Nghe hội thoại và chọn tranh đúng.',
    sortOrder: 5,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.LISTENING,
    fromNo: 17,
    toNo: 21,
    title: 'Nội dung trùng với đoạn hội thoại',
    titleKo: '대화 내용과 같은 것 고르기',
    description: 'Chọn câu mô tả đúng nội dung đã nghe.',
    sortOrder: 6,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.LISTENING,
    fromNo: 22,
    toNo: 24,
    title: 'Ý chính của người phụ nữ',
    titleKo: '여자의 중심 생각 고르기',
    description: 'Nghe và chọn ý chính của nhân vật nữ.',
    sortOrder: 7,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.LISTENING,
    fromNo: 25,
    toNo: 26,
    title: 'Nghe và trả lời (1)',
    titleKo: '듣고 물음에 답하기 (25–26)',
    description: 'Đoạn nghe dài hơn, 2 câu hỏi.',
    sortOrder: 8,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.LISTENING,
    fromNo: 27,
    toNo: 28,
    title: 'Nghe và trả lời (2)',
    titleKo: '듣고 물음에 답하기 (27–28)',
    sortOrder: 9,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.LISTENING,
    fromNo: 29,
    toNo: 30,
    title: 'Nghe và trả lời (3)',
    titleKo: '듣고 물음에 답하기 (29–30)',
    description: 'Câu hỏi tổng hợp và chọn nội dung trùng.',
    sortOrder: 10,
  },

  // —— 읽기 (40 câu) ——
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 1,
    toNo: 3,
    title: 'Đoạn nói về điều gì?',
    titleKo: '무엇에 대한 이야기입니까?',
    sortOrder: 1,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 4,
    toNo: 9,
    title: 'Chọn từ điền vào chỗ trống',
    titleKo: '( )에 들어갈 가장 알맞은 것',
    sortOrder: 2,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 10,
    toNo: 12,
    title: 'Chọn câu không đúng',
    titleKo: '맞지 않는 것 고르기',
    sortOrder: 3,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 13,
    toNo: 15,
    title: 'Chọn câu trùng nội dung',
    titleKo: '내용과 같은 것 고르기',
    sortOrder: 4,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 16,
    toNo: 18,
    title: 'Chọn ý chính',
    titleKo: '중심 생각 고르기',
    sortOrder: 5,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 19,
    toNo: 20,
    title: 'Đọc hiểu đoạn văn (1)',
    titleKo: '읽고 물음에 답하기 (19–20)',
    sortOrder: 6,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 21,
    toNo: 22,
    title: 'Đọc hiểu đoạn văn (2)',
    titleKo: '읽고 물음에 답하기 (21–22)',
    sortOrder: 7,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 23,
    toNo: 24,
    title: 'Đọc hiểu đoạn văn (3)',
    titleKo: '읽고 물음에 답하기 (23–24)',
    sortOrder: 8,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 25,
    toNo: 26,
    title: 'Đọc hiểu đoạn văn (4)',
    titleKo: '읽고 물음에 답하기 (25–26)',
    sortOrder: 9,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 27,
    toNo: 28,
    title: 'Sắp xếp câu đúng thứ tự',
    titleKo: '순서대로 맞게 나열하기',
    sortOrder: 10,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 29,
    toNo: 30,
    title: 'Chèn câu vào đoạn văn',
    titleKo: '문장 넣기 / 읽고 답하기 (29–30)',
    sortOrder: 11,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 31,
    toNo: 32,
    title: 'Đọc hiểu đoạn văn (5)',
    titleKo: '읽고 물음에 답하기 (31–32)',
    sortOrder: 12,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 33,
    toNo: 34,
    title: 'Đọc thông báo / quảng cáo',
    titleKo: '읽고 물음에 답하기 (33–34)',
    description: 'Thường là thông báo, poster, mục đích viết bài.',
    sortOrder: 13,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 35,
    toNo: 36,
    title: 'Đọc hiểu đoạn văn (6)',
    titleKo: '읽고 물음에 답하기 (35–36)',
    sortOrder: 14,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 37,
    toNo: 38,
    title: 'Đọc hiểu đoạn văn (7)',
    titleKo: '읽고 물음에 답하기 (37–38)',
    sortOrder: 15,
  },
  {
    tier: TopikTier.TOPIK_I,
    section: TopikSection.READING,
    fromNo: 39,
    toNo: 40,
    title: 'Đọc hiểu đoạn văn (8)',
    titleKo: '읽고 물음에 답하기 (39–40)',
    sortOrder: 16,
  },
];
